// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokDefmodule-0]
	_ = x[TokDef-1]
	_ = x[TokDefp-2]
	_ = x[TokDefmacro-3]
	_ = x[TokDefmacrop-4]
	_ = x[TokDefguard-5]
	_ = x[TokDefguardp-6]
	_ = x[TokDefdelegate-7]
	_ = x[TokDefprotocol-8]
	_ = x[TokDefimpl-9]
	_ = x[TokDefstruct-10]
	_ = x[TokDefexception-11]
	_ = x[TokAlias-12]
	_ = x[TokImport-13]
	_ = x[TokUse-14]
	_ = x[TokRequire-15]
	_ = x[TokDo-16]
	_ = x[TokEnd-17]
	_ = x[TokFn-18]
	_ = x[TokWhen-19]
	_ = x[TokIdent-20]
	_ = x[TokModule-21]
	_ = x[TokAttr-22]
	_ = x[TokAttrDoc-23]
	_ = x[TokAttrSpec-24]
	_ = x[TokAttrType-25]
	_ = x[TokAttrBehaviour-26]
	_ = x[TokAttrCallback-27]
	_ = x[TokString-28]
	_ = x[TokHeredoc-29]
	_ = x[TokSigil-30]
	_ = x[TokCharLiteral-31]
	_ = x[TokAtom-32]
	_ = x[TokDot-33]
	_ = x[TokComma-34]
	_ = x[TokColon-35]
	_ = x[TokOpenParen-36]
	_ = x[TokCloseParen-37]
	_ = x[TokOpenBracket-38]
	_ = x[TokCloseBracket-39]
	_ = x[TokOpenBrace-40]
	_ = x[TokCloseBrace-41]
	_ = x[TokOpenAngle-42]
	_ = x[TokCloseAngle-43]
	_ = x[TokPipe-44]
	_ = x[TokBackslash-45]
	_ = x[TokRightArrow-46]
	_ = x[TokLeftArrow-47]
	_ = x[TokAssoc-48]
	_ = x[TokDoubleColon-49]
	_ = x[TokPercent-50]
	_ = x[TokHEEXOpenTag-51]
	_ = x[TokHEEXCloseTag-52]
	_ = x[TokNumber-53]
	_ = x[TokComment-54]
	_ = x[TokEOL-55]
	_ = x[TokEOF-56]
	_ = x[TokOther-57]
}

const _TokenKind_name = "TokDefmoduleTokDefTokDefpTokDefmacroTokDefmacropTokDefguardTokDefguardpTokDefdelegateTokDefprotocolTokDefimplTokDefstructTokDefexceptionTokAliasTokImportTokUseTokRequireTokDoTokEndTokFnTokWhenTokIdentTokModuleTokAttrTokAttrDocTokAttrSpecTokAttrTypeTokAttrBehaviourTokAttrCallbackTokStringTokHeredocTokSigilTokCharLiteralTokAtomTokDotTokCommaTokColonTokOpenParenTokCloseParenTokOpenBracketTokCloseBracketTokOpenBraceTokCloseBraceTokOpenAngleTokCloseAngleTokPipeTokBackslashTokRightArrowTokLeftArrowTokAssocTokDoubleColonTokPercentTokHEEXOpenTagTokHEEXCloseTagTokNumberTokCommentTokEOLTokEOFTokOther"

var _TokenKind_index = [...]uint16{0, 12, 18, 25, 36, 48, 59, 71, 85, 99, 109, 121, 136, 144, 153, 159, 169, 174, 180, 185, 192, 200, 209, 216, 226, 237, 248, 264, 279, 288, 298, 306, 320, 327, 333, 341, 349, 361, 374, 388, 403, 415, 428, 440, 453, 460, 472, 485, 497, 505, 519, 529, 543, 558, 567, 577, 583, 589, 597}

func (i TokenKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
